name: ${rootProject.name}
version: ${rootProject.version}
api-version: '1.20'
main: com.noobnuby.plugin.Main
description: A template plugin
website: https://me.noobnuby.com
author: noobnuby

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22
  - org.jetbrains.kotlin:kotlin-reflect:1.9.22
  - xyz.icetang.lib:kommand-core:3.1.11